CREATE TABLE APP_USER (
    APP_USER_ID      VARCHAR(16)
        CONSTRAINT NN_APP_USER_ID      NOT NULL
        CONSTRAINT PK_APP_USER         PRIMARY KEY
  , EXTERNAL_USER_ID VARCHAR(16)
        CONSTRAINT NN_EXTERNAL_USER_ID NOT NULL
  , APP_GROUP        CHAR(1)
        CONSTRAINT NN_APP_GROUP        NOT NULL
);

CREATE INDEX IDX_APP_USER_EXTERNAL_USER_ID ON APP_USER (
    EXTERNAL_USER_ID ASC
);
